### ISSUE TITLE
Some players cannot connect to the server. 

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1505]
### Issue description
Hello, some of my players has a problem. They cannot connect to my server, or nothing doesn’t work. 

Why I decided to create an issue? I tested the latest version of PocketMine-MP and Steadfast2. Therefore, if I am connecting to the server with Steadfast2, everything is OK, but on the server based on PocketMine, anything like a commands or chat are not working, and the chunks are not loading.  

A video that shows the problem: [DropBox Link](https://www.dropbox.com/s/13lzwpgf7man6r1/video.mp4?dl=0)

PocketMine-MP: 19132
Steadfast2: 19140

Two servers are installed on my dedicated server (MC-32 OVH). 

### Steps to reproduce the issue
Unfortunately, I was not able to understand the cause of this problem..

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/a4ca3f1d1c92d2e6238fb68400355d5fe7038345
* Steadfast2: https://github.com/Hydreon/Steadfast2/commit/42fd893194141f617827a5c584b207fd47e79ecd
* PHP: 7.2.0RC4
* Server OS: CentOS 7.4.1708
* Game version: PE/Win10

### Plugins
- Game servers are tested without plugins.

### Crashdump, backtrace or other files
I can send you any types of debug logs or something like that if you want.

**Comment by veme312** [comment]
I can confirm it

**Comment by dktapps** [comment]
my best guess is that it's something to do with Steadfast2's lower maximum MTU size... that's not really solving such problems, but it would probably mitigate it... try lowering this 1464 to 1432 or lower and see if it resolves your issue (https://github.com/pmmp/RakLib/blob/master/server/OfflineMessageHandler.php#L58)

**Comment by dktapps** [comment]
I've pushed a bugfix to RakLib for another MTU size bug, please test https://github.com/pmmp/RakLib/commit/9142e7decec23b302ab470a55e5ed160df4878db

**Comment by zKoz210** [comment]
The last fix works! Thank you very much! <3

**Comment by zKoz210** [comment]
@dktapps In some people the problem persists, I have to put 1432 everytime I update of pmmp.

This happens on very old routers, which are supplied as an additional service from provider.

**Comment by dktapps** [comment]
Yes, I experienced the same problem on an old library router. As I recall, manually lowering the router MTU size to 1432 helped alleviate the issue. I've been experiencing that problem since at least 0.15, with vanilla and PocketMine both.

**Comment by dktapps** [comment]
MCPE would often crash or fail to connect at all.
